### ISSUE TITLE
A multi-stage example

### ISSUE THREAD

**Issue by uint** [kpcyrd/mini-docker-rust#5]
Hi!

Docker features multi-stage builds nowadays: https://docs.docker.com/develop/develop-images/multistage-build/

This pretty much lets you create a temporary build image, then copy an artifact from the build image over to your actual target image, all in one Dockerfile. Have you considered that approach? I got the same size from that, but I feel the Dockerfile is "cleaner".

```
tom@tomian:~/code/mini-docker-rust$ docker image ls
REPOSITORY              TAG                 IMAGE ID            CREATED              SIZE
mdrr                    latest              6dbc2cd0676e        11 seconds ago       7.52MB
mdr                     latest              0f65f756e698        9 minutes ago        7.52MB
<snip>
```

**Comment by uint** [comment]
Oh, and here's my Dockerfile for reference. I'm happy to create a PR.

```
FROM alpine:latest AS builder
COPY ./ /app
WORKDIR /app
RUN apk add --no-cache rust cargo \
    && cargo build --release

FROM alpine:latest
WORKDIR /
COPY --from=builder /app/target/release/mini-docker-rust .
RUN apk add --no-cache libgcc
ENTRYPOINT ["/mini-docker-rust"]
```

**Comment by kpcyrd** [comment]
I've updated it to a multi-stage build that is based on the rust:alpine image that became available recently. Thanks!
