### ISSUE TITLE
Minimize binary size

### ISSUE THREAD

**Issue by johnthagen** [kpcyrd/mini-docker-rust#6]
You could try to apply the techniques here to further reduce the final binary size: https://github.com/johnthagen/min-sized-rust

At a minimum, `strip`ing the binary should reduce the size significantly without any real cost: https://github.com/johnthagen/min-sized-rust#strip-symbols-from-binary

**Comment by kpcyrd** [comment]
hey!

Strip is a good suggestion, I think some of the others trade binary size for performance, which I'd like to avoid. :)

Do you want to submit a PR to get properly credited? Otherwise I'd commit the change myself.

**Comment by johnthagen** [comment]
> Do you want to submit a PR to get properly credited?

You can go ahead. No need for me to get credit, just wanted to help. 😄

**Comment by johnthagen** [comment]
Fixed in b72c40f8c89247c3c3d2d6bbcaf66dfb2e3c531b

**Comment by johnthagen** [comment]
@kpcyrd Is this statement in the README still accurate, or did it reduce in size? 

> The resulting image for a working hello world was about 8.1MB during my tests.

**Comment by kpcyrd** [comment]
Thanks for pointing that out, it's now 6.01MB!
